import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const url = api.example.getURL.useQuery();

  return (
    <>
      <Head>
        <title>Hitori</title>
        <meta
          name="description"
          content="Hitori bot generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-8 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Hitori{" "}
          </h1>
          <div className="flex items-center">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the core behind Hitori.
              </div>
            </Link>
          </div>
          <p className="text-2xl text-white">Get started</p>
          <code className="border-2 border-[#7162b0] bg-[#443867] p-4 font-mono text-gray-200">
            {url.data ? `${url.data}/api/bot` : "Loading..."}
          </code>
        </div>
      </main>
    </>
  );
};

export default Home;
